<?php
session_start();
require("db.php");


//code to update an item in the list will be written here
//get the user_id
$user_id = $_SESSION['user_id'];



//run a query to create new note
$sql = "INSERT INTO items (user_id, item_name, priority) VALUES ('$user_id', '', '')";

$result = mysqli_query($conn, $sql);
if(!$result){
    echo 'error';
}else{
    //this function returns the autogenerated id produced in the last query
    echo mysqli_insert_id($link);
}

?>